export enum BookGenreEnum {
  FANTASY = 'FANTASY',
  SCI_FI = 'SCI_FI',
  ROMANCE = 'ROMANCE',
  THRILLER = 'THRILLER',
  MYSTERY = 'MYSTERY',
  HORROR = 'HORROR',
  HISTORICAL = 'HISTORICAL',
  DRAMA = 'DRAMA',
  ADVENTURE = 'ADVENTURE',
  SLICE_OF_LIFE = 'SLICE_OF_LIFE',
}
